"""
verify_params.py -- exact quantum parameters of the flagship example (no invented
numbers: dimensions are computed from linear algebra, distances by brute force
over all codewords).

Model (all computations are exact, over F_4 = F_2(omega)):
  A = F_4 x F_4  (= F_4[v]/<v^2 - v>, v^2 = v),  n = 7,  kappa = 1  (Hermitian twist,
  q = 2 so that the 1-Galois inner product on F_{q^2} = F_4 is the Hermitian one).
  Component code  C_i = <f_i>  (lambda_i-constacyclic, lambda_i in {1, omega}),
  ring code       C  = C_1 x C_2  (an A-linear code of length n over A).
  Gray image      psi(C) = C_1 x C_2  inside F_4^{2n} = F_4^14  (natural identification).
  Quantum object  Hermitian CSS code of psi(C) (contains its Hermitian dual).
"""
from itertools import product
from fflib import GF, Poly, const, ord_of_poly, in_span
from fflib2 import code_basis, sigma_dual_basis
from fflib3 import divisors_fast
from verify_mechanism import xnf, _dual_containing
import math

F = GF(2, 2, [1, 1, 1])                     # F_4 = F_2[x]/(x^2+x+1)
OM = [a for a in F.nonzero() if F.order(a) == 3][0]
N = 7


def weight(v):
    return sum(1 for c in v if c != F.zero)


def min_weight(H, exclude=None):
    """brute-force minimum Hamming weight over the code generated by rows H."""
    rows = [r for r in H]
    k = len(rows)
    best, bestv = None, None
    for coeffs in product(F.elements(), repeat=k):
        w = [F.zero] * len(rows[0])
        for ci, r in zip(coeffs, rows):
            if ci != F.zero:
                w = [F.add(a, F.mul(ci, b)) for a, b in zip(w, r)]
        if all(c == F.zero for c in w):
            continue
        if exclude is not None and in_span(F, exclude, w):
            continue
        wt = weight(w)
        if best is None or wt < best:
            best, bestv = wt, w
    return best, bestv


def hermitian_dual_basis(F, C, n):
    return sigma_dual_basis(F, C, n, 1)          # q = 2: 1-Galois = Hermitian


def component_report(lam):
    xr = xnf(F, N, lam)
    ds = divisors_fast(F, xr)[0] if isinstance(divisors_fast(F, xr), tuple) else divisors_fast(F, xr)
    rows = []
    for g in ds:
        if g.deg() == 0 or g.deg() == N:
            continue
        o = ord_of_poly(F, g)
        dc = _dual_containing(F, N, lam, g, 1)
        Cb = code_basis(F, g, N, lam)
        dC, _ = min_weight(Cb)
        entry = dict(lam=lam, g=tuple(map(tuple, g.c)), deg=g.deg(), ord=o,
                     dual_containing=dc, kC=N - g.deg(), d=dC)
        if dc:
            Hd = hermitian_dual_basis(F, Cb, N)
            dH, _ = min_weight(Hd)
            dq, wq = min_weight(Cb, exclude=Hd)
            entry.update(dim_dual=len(Hd), d_dual=dH, d_quantum=dq,
                         k_quantum=2 * (N - g.deg()) - N)
        rows.append(entry)
    return rows


if __name__ == "__main__":
    print("=" * 100)
    print("Factorization of x^7 - lambda over F_4 and orders of the factors")
    print("=" * 100)
    for lam, name in [(F.one, "1"), (OM, "omega")]:
        xr = xnf(F, N, lam)
        ds = divisors_fast(F, xr)
        ds = ds[0] if isinstance(ds, tuple) else ds
        print(f"  x^7 - {name}:")
        seen = set()
        for d in ds:
            if d.deg() == 0:
                continue
            if tuple(map(tuple, d.c)) in seen:
                continue
            seen.add(tuple(map(tuple, d.c)))
            print(f"     factor deg {d.deg()}  ord_f(x) = {ord_of_poly(F, d):2d}   "
                  f"{(tuple(map(tuple, d.c)))}")
    print()
    print("=" * 100)
    print("Component codes (length 7 over F_4) and their Hermitian-CSS quantum parameters")
    print("=" * 100)
    print("  lam | deg g | ord_f | [7,k,d]_4     | dual-containing | [7, k']_4 dual | d(C^perp_H) | [[7, k_q, d_q]]_2")
    all_rows = []
    for lam, name in [(F.one, "1"), (OM, "omega")]:
        for r in component_report(lam):
            all_rows.append(r)
            extra = (f" | {r['d_dual']:11d} | [[7,{r['k_quantum']},{r['d_quantum']}]]_2"
                     if r["dual_containing"] else " |      -      |     -")
            print(f"  {name:>4} | {r['deg']:5d} | {r['ord']:5d} | [7,{r['kC']},{r['d']}]_4 "
                  f"| {str(r['dual_containing']):15s}{extra}")
    print()
    print("=" * 100)
    print("RING CODE  C = C_1 x C_2  with C_1 = <f_1> (lam=omega), C_2 = <f_2> (lam=1), deg f_i = 3")
    print("=" * 100)
    best = {}
    for lam, name in [(F.one, "1"), (OM, "omega")]:
        cands = [r for r in all_rows if r["lam"] == lam and r["dual_containing"]]
        cands.sort(key=lambda r: -r["ord"])
        print(f"  lambda = {name}: dual-containing divisors with largest ord_f: "
              f"deg={cands[0]['deg']}, ord={cands[0]['ord']}, [7,{cands[0]['kC']},{cands[0]['d']}]_4")
        best[name] = cands[0]
    # build the ring code C1 x C2 over F_4^{14} and its Hermitian dual
    g1 = Poly(F, list(map(tuple, best["omega"]["g"])))
    g2 = Poly(F, list(map(tuple, best["1"]["g"])))
    C1 = code_basis(F, g1, N, OM)
    C2 = code_basis(F, g2, N, F.one)
    ring_basis = [c1 + [F.zero] * N for c1 in C1] + [[F.zero] * N + c2 for c2 in C2]
    H1 = hermitian_dual_basis(F, C1, N)
    H2 = hermitian_dual_basis(F, C2, N)
    ring_dual = [h + [F.zero] * N for h in H1] + [[F.zero] * N + h for h in H2]
    print(f"  dim_F4 psi(C) = {len(ring_basis)}  over F_4^14   (qubits: 14)")
    print(f"  psi(C)^perp_H subset psi(C): {all(in_span(F, ring_basis, v) for v in ring_dual)}")
    print(f"  quantum dimension 2*8 - 14 = {2*len(ring_basis)//2 - 14}")
    dq, wq = min_weight(ring_basis, exclude=ring_dual)
    d_dual, _ = min_weight(ring_dual)
    d_code, wc = min_weight(ring_basis)
    print(f"  d(psi(C)) = {d_code}, d(psi(C)^perp_H) = {d_dual}, "
          f"d(psi(C) \\ psi(C)^perp_H) = {dq}  ->  [[14, 2, {dq}]]_2")
    print(f"  tolerance (lcm law): lcm(ord_f1, ord_f2) = lcm({best['omega']['ord']},"
          f"{best['1']['ord']}) = {math.lcm(best['omega']['ord'], best['1']['ord'])}"
          f"  ->  T <= {math.lcm(best['omega']['ord'], best['1']['ord']) - 1} > n = {N}")
    L = 14 + (math.lcm(best["omega"]["ord"], best["1"]["ord"]) - 1)
    print(f"  resulting QSC family: [[14 + T, 2, {dq}]]_2 with T <= "
          f"{math.lcm(best['omega']['ord'], best['1']['ord']) - 1};  maximal length {L} qubits,"
          f"  T/L = {(L-14)/L:.3f}")
